#!/bin/bash
# chkconfig: 345 98 20
# description: Watch system status
# processname: inotifywait
#############################################################
# watch dir
NOTIFYPATH=/home/sftp/product

# buffer time
TIMEOUT=5

# lock file
LOCK=/var/lock/subsys/inotifywait
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network

RETVAL=0
start() {
echo -n $"inotifywait started: "
/usr/bin/inotifywait -e modify,attrib,create,delete \
--format '%w%f %e %T' \
--timefmt '%Y/%m/%d-%H:%M:%S' \
--exclude '.*\.sw[pox].*' \
-mrq ${NOTIFYPATH} | while [ 1 ]; do
  messages=""
  while read -t $TIMEOUT line; do
    messages="${messages}$line@RET@"
  done
  if [ -n "$messages" ]; then
    #action
    /usr/local/pssh/bin/prsync -x --delete -h /root/pssh/nodelist/web -a /home/sftp/product /home/sftp/ > /dev/null 2>&1
    #echo $messages | sed 's/@RET@/\n/g' | \
    #/usr/bin/Mail -s "${TITLE} `hostname` ${NOTIFYPATH}" $MAILTO
  fi
done &
RETVAL=$?
echo
[ $RETVAL -eq 0 ] && touch $LOCK
return $RETVAL
}
stop() {
echo -n $"inotifywait stopped: "
killproc inotifywait
RETVAL=$?
echo
[ $RETVAL -eq 0 ] && rm -f $LOCK
return $RETVAL
}
case "$1" in
start)
start
;;
stop)
stop
;;
status)
status inotifywait
;;
restart)
stop
start
;;
*)
echo $"Usage: $0 {start|stop|status|restart}"
exit 1
esac
exit $?
